version: 2.1

# Prerequisite
# Make sure you set secret enviroment variables in CICD
# DOCKER_USERNAME
# DOCKER_PASSWORD
# API_TOKEN

# REBUILD - it has default value "false", if need rebuild the image, turn it on with value "true"

parameters:
  rebuild:
    type: string
    default: "false"

jobs:
  build:
    machine: true
    environment:
      REBUILD: << pipeline.parameters.rebuild >>
    steps:
      - checkout
      - run: |
          echo $REBUILD
          bash ./build.sh

  scan:
    docker:
      - image: alpine/trivy
    steps:
      - checkout
      - run: |
          trivy image --format table --exit-code 1 \
             --ignore-unfixed --vuln-type os,library \
             --scanners vuln --severity CRITICAL,HIGH \
             --timeout 10m0s alpine/doctl \
             --db-repository public.ecr.aws/aquasecurity/trivy-db

workflows:
  build:
    jobs:
      - build:
          name: build
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main
      - scan:
          requires:
            - build
          name: scan
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main

  nightly:
    triggers:
       - schedule:
           cron: "0 2 * * *"
           filters:
             branches:
               only:
                 - master
                 - main
    jobs:
      - build:
          name: build
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main
      - scan:
          requires:
            - build
          name: scan
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main
